### ISSUE TITLE
how to register smpl model to scans？

### ISSUE THREAD

**Issue by hitlxm** [sergeyprokudin/smplpix#1]
a great job ！
i want to know how to create training data？how to register smpl model to my scans？
thanks！

**Comment by sergeyprokudin** [comment]
Hi! 

Unfortunately, we do not provide the registration code in the repository. Internally, we used something close to the method that was originally described in [the FAUST paper](https://files.is.tue.mpg.de/black/papers/FAUST2014.pdf).

In general, however, there are lots of methods to register SMPL model to scans, I can recommend checking [the leaderboard for the FAUST dataset](http://faust.is.tue.mpg.de/challenge/Intra-subject_challenge) to get an overview of the literature.

You can also try the code from our [ICCV 2019 paper](https://github.com/sergeyprokudin/bps) which offers a pre-trained regression model for the task:

You can then start with this initial predicted alignment and optimise it further with something like an [iterative closest point algorithm](https://en.wikipedia.org/wiki/Iterative_closest_point).

Hope this helps,

Sergey

![image](https://user-images.githubusercontent.com/8117267/118113949-3c92c100-b3e7-11eb-8e36-a521f92b5606.png)
