### ISSUE TITLE
Colorful mesh input

### ISSUE THREAD

**Issue by korenleven** [sergeyprokudin/smplpix#12]
Hi,
I'm getting hard to understand how to export the colorful mesh from Smplify-X
I'm succeed to export .obj file and overlay mesh image but not the colorful mesh that smplpix train on.
Can you shed light on how to do it?

**Comment by sergeyprokudin** [comment]
Hi korenleven,

the coloured SMPL-x mesh itself is located [here](https://github.com/sergeyprokudin/smplify-x/blob/master/smplifyx/smplx_verts_colors.txt). I would also recommend checking [the provided Colab with the data preparation pipeline](https://colab.research.google.com/github/sergeyprokudin/smplpix/blob/main/colab_notebooks/Convert_Video_to_SMPLpix_Dataset.ipynb).

Hope this helps,

~Sergey

**Comment by YJK-forDev** [comment]
@korenleven How did you fixed it? With the colab code, I have no colored mesh yet. I want to know where did you use the mesh file.

**Comment by felixshing** [comment]
> @korenleven How did you fixed it? With the colab code, I have no colored mesh yet. I want to know where did you use the mesh file.

Hi, I met this same problem. My output contains the SMPL mesh, SMPLX parameters, and an image showing the overlay between the estimated mesh and the original image, like the following. Did you solve this issue?

![image](https://github.com/sergeyprokudin/smplpix/assets/61814345/19db91a9-fd8f-405e-a035-1e61c2b62891)
