### ISSUE TITLE
How to get 3d avatar with texture from image/video?

### ISSUE THREAD

**Issue by bhumikasinghrk** [sergeyprokudin/smplpix#13]
Hi @sergeyprokudin,
I read the documentation but it still couldn't answer few questions i had. i was hoping you could help me.
Q. My aim is to generate a 3D Avatar with texture , given an image/video as input. If this is possible with this framework, how ? I can't locate any checkpoint or an inference file for that.

**Comment by sergeyprokudin** [comment]
Hi Bhumika! If what you mean by texture is a classical uv-map image, this framework is not suited for this. Here, we use neural networks to do the photorealistic rendering having some textureless (or coarsely textured) mesh as input. 

If you're interested in obtaining some classical uv-maps, it might be worth investigating DensePose framework (e.g., here's [the issue](https://github.com/facebookresearch/DensePose/issues/68) discussing something similar). Also, [some recent work](https://github.com/xuxy09/Texformer) on the topic.

Hope this helps! Let me know if you have any other questions,

~Sergey
