### ISSUE TITLE
Unable to upload video in colab demo

### ISSUE THREAD

**Issue by sparshgarg23** [sergeyprokudin/smplpix#14]
@sergeyprokudin  Hi,thanks for releasing the code.I tried to use the colab to get an understanding of how the code works,but it seems I am unable to upload a youtube video.
When I pass the youtube url
https://www.youtube.com/watch?v=gFr0_ywVdhY,it gives me an error  YOTUBE_VIDEO_URL  =   #@param.
The same holds when I select google drive/upload my own video.
Any idea why this is happening.

Also,as mentioned in  issue #4 ,is it possible to use mediapipe instead of openpose,if yes then I would really appreciate it if you could give me some suggestions on how to use the mediapipe results ,because the output of mediapipe and openpose are different.
Thanks

**Comment by sergeyprokudin** [comment]
Hi @sparshgarg23,

to upload the youtube video, you simply need to change the VIDEO_SOURCE drop menu in the cell:
 
![image](https://user-images.githubusercontent.com/8117267/148966018-01f5e25a-422c-4543-bf13-dd23b8cbafdb.png)

The download then works for me.

As for the mediapipe question, I didn't try it myself, so cannot provide detailed instruction. If the output format of mediapipe keypoints is equal to openpose, you'll simply need to modify the openpose cells in the provided colab notebook and adjust the locations for SMPLify-x inputs. However, if the keypoint format is different, you'll also need to adjust the [SMPLify-X optimisation pipeline](https://github.com/vchoutas/smplify-x) itself, which could be trickier. 

Hope this helps!

~Sergey

**Comment by sparshgarg23** [comment]
Thanks,I was able to get the video upload working,
As for the mediapipe issue,there is an opensource project called easymocap by ZJU3DV,which provides some wrappers for converting mediapipe to openpose.
Also during the fitting ,I ran into NAN loss,stop iteration.
I went and checked the openpose outputs,and for the video which I had uploaded I saw that  for certain images,the keypoint detection wasn't correct as observed here
1
![00060_rendered](https://user-images.githubusercontent.com/34626942/148968428-48c04388-12c1-4239-97ae-6bbeb8cd689b.png))
Also I noticed that when person is wearing glasses as shown in this picture,even then smplx wouldn't fit on that,even though hand and face keypoints were detected
![douche_rendered](https://user-images.githubusercontent.com/34626942/148968591-b38cec3c-d8f4-4dca-b4f4-ddcdf49d21ac.png)
Finally,I noticed the camera optimization loss was very high in the range of 14,000 is that normal behaviour?

Based on this 
I am thinking of trying with a different video which contains single people,standing in normal poses.
Because in the below mentioned example, smplx was able to  perform the fitting correctly(acc to me,)
Let me know if you have any suggestions.
Oh and the below mentioned result got me really excited  thinking that yes it can work on any video(but that 's just me)
[Open pose keypoint on first frame]
![00001_rendered](https://user-images.githubusercontent.com/34626942/148969423-b8e7d4f5-ae42-4015-8ba9-a45be09f5479.png)
[SMPLX fitting]
![00000](https://user-images.githubusercontent.com/34626942/148969496-bfca810a-c472-409e-af44-8650695bfb98.png)

I look forward to hearing from your end,and thank you again for opensourcing the project.

**Comment by sergeyprokudin** [comment]
Hi @sparshgarg23,

first, sorry for the late reply on this! Regarding your experience with non-full-body frames, it's a common problem for SMPLify-X, and nans are likely caused by it. 

As a workaround, I might try some different methods for SMPL body estimation, e.g. recent [PIXIE framework](https://github.com/YadiraF/PIXIE), [METRO](https://github.com/microsoft/MeshTransformer) or [PyMAF](https://hongwenzhang.github.io/pymaf/). I didn't try it myself yet though. The proper way would, of course, be to understand the core problem with SMPLify-x optimisation in the case of non-full-body :)

Hope this helps somehow, and thanks for sharing your results!

~Sergey

**Comment by sparshgarg23** [comment]
thanks for sharing the resources i will look into them
