### ISSUE TITLE
'Flatten the video into frames' error message

### ISSUE THREAD

**Issue by arnaudskyvr** [sergeyprokudin/smplpix#15]
Hello Sergey and thanks for the amazing work you did.

I was trying to run your colab and was able to upload my video (from google drive), but when I got to the second part ("Flatten the video into frames") I'm getting a fail with the following error message below, thanks in advance for your help:

ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
: No such file or directory

---------------------------------------------------------------------------

IndexError                                Traceback (most recent call last)

<ipython-input-2-0605769a26e7> in <module>()
     23   return np.asarray(Image.open(img_path))/255
     24 
---> 25 test_img_path = os.path.join(FRAMES_DIR, os.listdir(FRAMES_DIR)[0])
     26 
     27 test_img = load_img(test_img_path)

IndexError: list index out of range

**Comment by sergeyprokudin** [comment]
Hi @arnaudskyvr ,

it looks like the video you provided as a path wasn't found, hence no images are extracted by ffmpeg. Did you change the video source parameter to "google drive" in the corresponding cell?

![image](https://user-images.githubusercontent.com/8117267/150575334-6a2ad56d-4b24-47a4-804b-5cc75bbc21fa.png)

~Sergey

**Comment by arnaudskyvr** [comment]
It's actually quite strange cause the first step seemed to work fine, here is a screen capture. 
<img width="1440" alt="ErrorFile01" src="https://user-images.githubusercontent.com/55511020/150650847-8eeafe80-5ece-4e83-b94e-51a55645bd39.png">

**Comment by sergeyprokudin** [comment]
Hi @arnaudskyvr,

you should provide a mounted google drive path in the local file system, not the HTTP link. It should be something like '/content/gdrive/My Drive/path/to/video'. 

Hope this helps,

~Sergey

**Comment by arnaudskyvr** [comment]
Ah I see, thanks Sergey for this precious info, though in the meantime I had tried to upload that same video file to YouTube and I'm not getting an another error message:

![ErrorFile02](https://user-images.githubusercontent.com/55511020/150699363-121267e0-bad9-46a6-a3dc-c3ca959463ad.jpg)

![ErrorFile03](https://user-images.githubusercontent.com/55511020/150699369-4aee5d11-4430-472e-a32f-553827485ac6.jpg)

**Comment by sergeyprokudin** [comment]
this looks like a problem with [pytube](https://pytube.io/en/latest/) package, which failed to download the video from the provided youtube link. It happens sometimes, one would need to understand the underlying reason and probably create an issue in the pytube repository if needed.

~Sergey

**Comment by ss8319** [comment]
Hi @sergeyprokudin.
This  is similar error but it should be from a different source. I checked that the video I uploaded was done correctly in the previous cell. Any advise on this?

`ffmpeg version 3.4.11-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/content/Salvadorian_1.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    creation_time   : 2021-08-25T23:28:15.000000Z
  Duration: 00:00:31.51, start: 0.000000, bitrate: 10955 kb/s
    Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 10646 kb/s, 59.94 fps, 59.94 tbr, 60k tbn, 119.88 tbc (default)
    Metadata:
      creation_time   : 2021-08-25T23:28:15.000000Z
      handler_name    : Alias Data Handler
      encoder         : AVC Coding
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s (default)
    Metadata:
      creation_time   : 2021-08-25T23:28:15.000000Z
      handler_name    : Alias Data Handler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to '$FRAMES_DIR/%05d.png':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    encoder         : Lavf57.83.100
    Stream #0:0(eng): Video: png, rgb24, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 1 fps, 1 tbn, 1 tbc (default)
    Metadata:
      creation_time   : 2021-08-25T23:28:15.000000Z
      handler_name    : Alias Data Handler
      encoder         : Lavc57.107.100 png
[image2 @ 0x55a7d606be00] Could not open file : $FRAMES_DIR/00001.png
av_interleaved_write_frame(): Input/output error
frame=    4 fps=0.0 q=-0.0 Lsize=N/A time=00:00:01.00 bitrate=N/A speed=1.64x    
video:1475kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-5-73a0be7e8d8e>](https://localhost:8080/#) in <module>
     23   return np.asarray(Image.open(img_path))/255
     24 
---> 25 test_img_path = os.path.join(FRAMES_DIR, os.listdir(FRAMES_DIR)[0])
     26 
     27 test_img = load_img(test_img_path)

IndexError: list index out of range`

**Comment by Liyi980** [comment]
Hi, I met the same problem , but I can't find a way to solve it.\
My source is "upload" .
This is the error image:
"      encoder         : Lavc58.134.100 png
[image2 @ 0x598e542ee4c0] Could not open file : $FRAMES_DIR/00001.png
av_interleaved_write_frame(): Input/output error
frame=    2 fps=0.0 q=-0.0 Lsize=N/A time=00:00:01.00 bitrate=N/A speed=2.51x    
video:376kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

---------------------------------------------------------------------------

IndexError                                Traceback (most recent call last)

<ipython-input-4-0605769a26e7> in <cell line: 25>()
     23   return np.asarray(Image.open(img_path))/255
     24 
---> 25 test_img_path = os.path.join(FRAMES_DIR, os.listdir(FRAMES_DIR)[0])
     26 
     27 test_img = load_img(test_img_path)

IndexError: list index out of range

"
