### ISSUE TITLE
Render smplx model with vertex color seems weird

### ISSUE THREAD

**Issue by WhitKey** [sergeyprokudin/smplpix#16]
hello, I want to save my smplx model(same format on https://smpl-x.is.tue.mpg.de/) with your vertex color file(smplx_verts_colors.txt), but it seems weird when I check my model.
Is your smplx vertex order different to the smplx model which official website provides?
![image](https://user-images.githubusercontent.com/65229869/154310956-ebd5443f-2ab2-4eae-ab91-6d24cf2ec64a.png)

**Comment by sergeyprokudin** [comment]
Hi @WhitKey,

the vertex order corresponds to SMPL-X mesh loaded as Trimesh object, you might want to check [this piece for reference](https://github.com/sergeyprokudin/smplify-x/blob/74e112507b07c821d55411db916c5a6fc6cf45e5/smplifyx/fit_single_frame.py#L565).

Hope this helps,

~Sergey
