### ISSUE TITLE
The problem about data

### ISSUE THREAD

**Issue by jsxyzb** [sergeyprokudin/smplpix#18]
The data( https://www.dropbox.com/s/coapl05ahqalh09/smplpix_data_test_final.zip?dl=0 ) can't be download. Are you sure the zip file is correct?

**Comment by sergeyprokudin** [comment]
Hi @jsxyzb,

I just checked: the link is correct and working. Just in case, I've also uploaded the data [here](https://drive.google.com/file/d/1hxwvQvtJ7ne0GGS6g2c3ME1m-i6AmgA7/view?usp=sharing). 

Hope this helps,

~Sergey
