### ISSUE TITLE
Get 3d textured model

### ISSUE THREAD

**Issue by kashyappiyush1998** [sergeyprokudin/smplpix#19]
How do I get the corresponding SMPL textured model for my video with vertex color or UV map for my video input?
As in #16 smplx_verts_colors.txt and the output from where do I get those

**Comment by sergeyprokudin** [comment]
Hi @kashyappiyush1998 ,

you can find the vertex colours [here](https://github.com/sergeyprokudin/smplify-x/blob/master/smplifyx/smplx_verts_colors.txt).

Hope it helps,
~Sergey

**Comment by kashyappiyush1998** [comment]
This is a constant txt file, right? Is there a way to get vertex colors and SMPL model generated from video?
Thanks

**Comment by sergeyprokudin** [comment]
you can get the SMPL model params (via [SMPlify-x framework](https://colab.research.google.com/github//sergeyprokudin/smplpix/blob/main/colab_notebooks/Convert_Video_to_SMPLpix_Dataset.ipynb)), but the appearance information itself is generated via the trained rendering network, not stored explicitly.

**Comment by kashyappiyush1998** [comment]
Thanks, I will try on your repo for [smplify-x]. I just had one more question,is there to achieve this using newer method like EXPOSE, which have better performance when it comes to time. I have tried Smplpix and it works using https://github.com/vchoutas/expose , however colour will be a issue there. Is there a general method to generate color.

**Comment by sergeyprokudin** [comment]
sure, you can try regression-based methods like expose or more recent works (e.g. [PARE](https://github.com/mkocabas/PARE) or [PIXIE](https://github.com/YadiraF/PIXIE)), but optimisation-based methods give better alignment of 3D mesh and observed body keypoints, which simplifies rendering training step.

For inferring uv maps directly, check this [issue](https://github.com/sergeyprokudin/smplpix/issues/13#issuecomment-980536126). Short version: try Densepose or [Texformer](https://github.com/xuxy09/Texformer).
