### ISSUE TITLE
Rendering meshes.

### ISSUE THREAD

**Issue by AIMads** [sergeyprokudin/smplpix#23]
Hey first of all great work!

Im getting issues when trying to Run SMPLify-X, the program is processing, but the output is the mesh file but not an image render which can be used for training. How do I solve this?

**Comment by AIMads** [comment]
Okay fixed the issue, but it is rather severe. 

Steps:
1. in colab change from python3.7 to 3.8
    #install python 3.8
    !sudo apt-get update -y
    !sudo apt-get install python3.8

    #change alternatives
    !sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
    !sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 2

    #check python version
    !python --version
2. Install all packages
3. Pytorch problem which best is fixed as described in:
https://stackoverflow.com/questions/65637222/runtimeerror-subtraction-the-operator-with-a-bool-tensor-is-not-supported 

Overall the reason is pyglet2.0 which has a requirement for python3.8. This is what is breaking the system.

**Comment by ss8319** [comment]
@AIMads, would you mind sharing your colab notebook that u got working? I seem to be running into a CUDA memory error #24. I have opened a new issue already.
