### ISSUE TITLE
The implementation of Equation 4 

### ISSUE THREAD

**Issue by HowieMa** [sergeyprokudin/smplpix#25]
Hi Sergey,
Thanks for sharing this excellent work. I am a novice in 3D mesh area. May I ask where is the implementation of Equation 4 in your paper? It seems that the dataloader directly load the pre-processed images P_X from Colab. Thus, I'd like to know your detailed implementation of these pre-processing part. 
Looking forward to your reply. Thanks!

**Comment by sergeyprokudin** [comment]
Hi @HowieMa, this repository doesn't have the implementation for point-rendering. However, I can recommend exploring the [pytorch3d](https://pytorch3d.org/) library for point rendering techniques. E.g., here's an [example](https://pytorch3d.org/tutorials/render_colored_points) of rendering a point cloud.

**Comment by HowieMa** [comment]
Hi Sergey, thanks for your explanation and suggestions. That's very helpful!
