### ISSUE TITLE
How to do multi-view fusion to achieve 6DoF volumetric video rendering?

### ISSUE THREAD

**Issue by felixshing** [sergeyprokudin/smplpix#27]
Hello, in my use case, I have four rgb-d cameras for capturing so I can get rendering results from multiple views. How should I merge the results from different views in order to gain 6DoF volumetric content rendering?

**Comment by sergeyprokudin** [comment]
Hi @felixshing, in your case, you need to first do the camera calibration to acquire the extrinsic parameters of the cameras (with e.g. COLMAP). Then, you might want to consider tools like [EasyMocap](https://github.com/zju3dv/EasyMocap) to get the SMPL-X estimates from multiple views. You might also want to consider more recent works on the volumetric human rendering, e.g. [NeuralBody](https://github.com/zju3dv/neuralbody) and its follow-ups.

Hope this helps!

~Sergey

**Comment by felixshing** [comment]
Thank you, I will investigate these repos. Thank you very much for your guidance and recommendation!
