### ISSUE TITLE
Colab connect to local runtime

### ISSUE THREAD

**Issue by asdqe5** [sergeyprokudin/smplpix#3]
I have a question about excuting colab by connecting to local runtime.
I just connect this colab to my local server, but I don't know how to excute this colab by file in my local.
Could it be excuted in local runtime?

and.. I think there are some problems in Openpose installation or Running OpenPose on the extracted frames. Becaus it was doing well yesterday, but today it's not..

I appreciate for this project
Thank you.

**Comment by sergeyprokudin** [comment]
Hi!

> Could it be excuted in local runtime?

Sure, you'd just need to adjust the paths to datasets\models and make sure you have an Internet connection (for installing the dependencies).

>I think there are some problems in Openpose installation or Running OpenPose

yes, this happens sometimes as the OpenPose server goes down, check [this issue](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1933) for more details. Basically, you can either follow the advices there or just wait until the server will come back to life.
