### ISSUE TITLE
Mediapipe pose use instead of openpose

### ISSUE THREAD

**Issue by 1kaiser** [sergeyprokudin/smplpix#4]
Media pipe pose use instead of open pose because it throws building error

https://colab.research.google.com/drive/1uCuA6We9T5r0WljspEHWPHXCT_2bMKUy

https://google.github.io/mediapipe/solutions/holistic

**Comment by 1kaiser** [comment]
https://colab.research.google.com/drive/1uCuA6We9T5r0WljspEHWPHXCT_2bMKUy

**Comment by sergeyprokudin** [comment]
Hi,

I'll add a workaround for this in the next few days. Until that, you can use [the following solution](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1933#issuecomment-830645892) and copy the necessary OpenPose models' files from the Kaggle repository:

**Comment by 1kaiser** [comment]
@sergeyprokudin can you please make a video running the Google colaboratory versions and post it on you tube. So that the process where we get struck.. we can replicate your steps for overcoming the problems.  Screen capture video.

**Comment by sergeyprokudin** [comment]
Hi @1kaiser! I might add it later, but for now, you can simply tell me at which cell you start experiencing problems. I just checked  [the latest Colab demo](https://colab.research.google.com/github//sergeyprokudin/smplpix/blob/main/colab_notebooks/Convert_Video_to_SMPLpix_Dataset.ipynb) and it runs OK.

**Comment by 1kaiser** [comment]
Okay, i will try.

**Comment by 1kaiser** [comment]
error from last cell

```
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-24-397f5e2204f0> in <module>()
     27 get_ipython().system('mkdir -p $test_output_dir')
     28 






---> 29 img_names = sorted(os.listdir(target_images_path))
     30 n_images = len(img_names)
     31 n_train_images = int(n_images * train_ratio)

FileNotFoundError: [Errno 2] No such file or directory: '/content/data/smplifyx_results/input_images'
```

**Comment by sergeyprokudin** [comment]
> ### **_error from last cell_**
> `aN loss value, stopping! Camera initialization done after 1.2331 Processing: /content/data/images/unscreen-144.png Found Trained Model: /content/vposer/vposer_v1_0/snapshots/TR00_E096.pt NaN loss value, stopping! Camera initialization done after 1.2303 Processing the data took: 00 hours, 03 minutes, 03 seconds`
> 
> ### **_ after running this ::_**
> `# @title Make train-test-validation splits, copy data to final folders
> 
> import shutil
> 
> train_ratio = 0.9 #@param
> 
> final_zip_path = '/content/gdrive/MyDrive/PRINT/G/kaiser/images/smplpix_data_test.zip' # @param {type:"string"}
> 
> target_images_path = '/content/data/smplifyx_results/input_images'
> smplifyx_renders = '/content/data/smplifyx_results/rendered_smplifyx_meshes'
> 
> smplpix_data_path = '/content/smplpix_data'
> 
> train_input_dir = os.path.join(smplpix_data_path, 'train', 'input')
> train_output_dir = os.path.join(smplpix_data_path, 'train', 'output')
> val_input_dir = os.path.join(smplpix_data_path, 'validation', 'input')
> val_output_dir = os.path.join(smplpix_data_path, 'validation', 'output')
> test_input_dir = os.path.join(smplpix_data_path, 'test', 'input')
> test_output_dir = os.path.join(smplpix_data_path, 'test', 'output')
> 
> !mkdir -p $train_input_dir
> !mkdir -p $train_output_dir
> !mkdir -p $val_input_dir
> !mkdir -p $val_output_dir
> !mkdir -p $test_input_dir
> !mkdir -p $test_output_dir
> 
> img_names = sorted(os.listdir(target_images_path))
> n_images = len(img_names)
> n_train_images = int(n_images * train_ratio)
> n_val_images = int(n_images * (1-train_ratio) / 2)
> train_images = img_names[0:n_train_images]
> val_images = img_names[n_train_images:n_train_images+n_val_images]
> test_images = img_names[n_train_images:]
> 
> for img in train_images:
> shutil.copy(os.path.join(smplifyx_renders, img), train_input_dir)
> shutil.copy(os.path.join(target_images_path, img), train_output_dir)
> 
> for img in val_images:
> shutil.copy(os.path.join(smplifyx_renders, img), val_input_dir)
> shutil.copy(os.path.join(target_images_path, img), val_output_dir)
> 
> for img in test_images:
> shutil.copy(os.path.join(smplifyx_renders, img), test_input_dir)
> shutil.copy(os.path.join(target_images_path, img), test_output_dir)
> 
> %cd /content
> !zip -r $final_zip_path smplpix_data/`
> 
> ### _**error**_
> ```
> FileNotFoundError                         Traceback (most recent call last)
> <ipython-input-24-397f5e2204f0> in <module>()
>      27 get_ipython().system('mkdir -p $test_output_dir')
>      28 
> 
> 
> 
> 
> 
> 
> ---> 29 img_names = sorted(os.listdir(target_images_path))
>      30 n_images = len(img_names)
>      31 n_train_images = int(n_images * train_ratio)
> 
> FileNotFoundError: [Errno 2] No such file or directory: '/content/data/smplifyx_results/input_images'
> ```

this looks like a SMPLify-X error. Are you experiencing it when running the code on demo data or your own?

**Comment by 1kaiser** [comment]
Own data

**Comment by sergeyprokudin** [comment]
I would recommend then creating an issue at the [SMPLify-X](https://github.com/vchoutas/smplify-x) repository. It is highly likely that the optimisation is failing on your input frames for some reason (e.g. bad OpenPose detections).

**Comment by 1kaiser** [comment]
Ok i will try with high quality data, thanks 🙏🏻

**Comment by ss8319** [comment]
> Hi,
> 
> I'll add a workaround for this in the next few days. Until that, you can use [the following solution](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1933#issuecomment-830645892) and copy the necessary OpenPose models' files from the Kaggle repository:

Hi @sergeyprokudin @1kaiser 

Did you manage to get MediaPipe connected? Mind sharing your Colab notebook?
