### ISSUE TITLE
Some problems with custom data!

### ISSUE THREAD

**Issue by JanaldoChen** [sergeyprokudin/smplpix#5]
Thank you for your great work! When I train on my own data, I find that there are always color darkness inconsistencies between the rendered images and the ground truth.
![000537](https://user-images.githubusercontent.com/44859515/129701456-23d8d3b4-2beb-44d3-9049-829dd3c3b035.png)
I also trained on the demo data you provided and met the same problem.
![00000](https://user-images.githubusercontent.com/44859515/129701595-7e1d7cc3-444d-4a27-a93d-2a3fcc8bd785.png)

**Comment by sergeyprokudin** [comment]
Hi Janaldo,

thanks for sharing your experience! Cannot yet see the images though; in any case, try playing with the [VGG feature loss weighting](https://github.com/sergeyprokudin/smplpix/blob/60fea7321e702d6ef09f720db125b0d3e784fb66/smplpix/training.py#L18). I've actually just changed the default weights for the ones that behave a bit better on the variety of tasks, i.e. setting first layer weight to 1. You can try it now and report if the problem still persists.

Cheers,
Sergey

**Comment by JanaldoChen** [comment]
Thank you for your quick reply and I will try again according to your suggestion.

**Comment by felixshing** [comment]
Hello, I would like to ask how you generate your dataset, specifically, how you generated colored rendered image as the input

My output contains the SMPL mesh, SMPLX parameters, and an image showing the overlay between the estimated mesh and the original image, like the following. 

![image](https://github.com/sergeyprokudin/smplpix/assets/61814345/1c565a2a-4f1c-47d1-a00e-c8d4b34b53d2)
