### ISSUE TITLE
How to render faces only?

### ISSUE THREAD

**Issue by ribeiro-hugo** [sergeyprokudin/smplpix#6]
I'm trying to use the Google Colab on a video showing only face and shoulders, but I'm getting random results. Do I need to change any configuration?

**Comment by sergeyprokudin** [comment]
Hi Hugo!

Unfortunately, that's a known problem of SMPLify-X optimisation which is tailored to full body frames. If you are interested in face regions only, you may want to try estimating [FLAME face meshes](https://flame.is.tue.mpg.de/) only using [the DECA framework](https://github.com/YadiraF/DECA).

If you are actually interested in face+shoulder areas, you may want to try some of the recent mesh regression methods like [PyMAF](https://github.com/HongwenZhang/PyMAF) which might provide better results on partially observed bodies. I haven't tried it myself yet though, so would love to hear your outcome!

Hope this helps, 

~Sergey
