### ISSUE TITLE
how the model work for test images?

### ISSUE THREAD

**Issue by orydatadudes** [sergeyprokudin/smplpix#9]
i just can't understand if there is only one model for all images, how it's possible to know how to generate  the new unseen test humans ?
the model gets only the 3d   smpl

**Comment by sergeyprokudin** [comment]
hi @orydatadudes, 

the model released is the per-subject model as mentioned in the [readme](https://github.com/sergeyprokudin/smplpix/blob/main/README.md). The original multi-subject model (which is not a part of this repo) uses per-vertex colours and displacements to generate a subject-specific appearance.
